// { "framework": "Weex" }
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ (function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(1)
	var __weex_style__ = __webpack_require__(2)
	var __weex_script__ = __webpack_require__(3)

	__weex_define__('@weex-component/bc99dfe2a19b8cae6fcf6579e6911a1c', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})

	__weex_bootstrap__('@weex-component/bc99dfe2a19b8cae6fcf6579e6911a1c',undefined,undefined)

/***/ }),
/* 1 */
/***/ (function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": [
	    "container"
	  ],
	  "children": [
	    {
	      "type": "div",
	      "classList": [
	        "logoContainer"
	      ],
	      "children": [
	        {
	          "type": "image",
	          "classList": [
	            "logo"
	          ],
	          "attr": {
	            "src": "https://t.cn/Rq9bcDm"
	          }
	        },
	        {
	          "type": "text",
	          "classList": [
	            "desc"
	          ],
	          "attr": {
	            "value": "A framework for building Mobile cross-platform UI"
	          }
	        }
	      ]
	    },
	    {
	      "type": "div",
	      "classList": [
	        "textContainer"
	      ],
	      "children": [
	        {
	          "type": "text",
	          "classList": [
	            "text"
	          ],
	          "attr": {
	            "value": "Hello weex"
	          }
	        }
	      ]
	    }
	  ]
	}

/***/ }),
/* 2 */
/***/ (function(module, exports) {

	module.exports = {
	  "logoContainer": {
	    "width": 750,
	    "height": 500,
	    "alignItems": "center",
	    "justifyContent": "center",
	    "backgroundColor": "#0054dc"
	  },
	  "logo": {
	    "width": 378,
	    "height": 84
	  },
	  "desc": {
	    "marginTop": 40,
	    "fontSize": 24,
	    "color": "#cccccc"
	  },
	  "textContainer": {
	    "width": 750,
	    "paddingTop": 200,
	    "alignItems": "center",
	    "justifyContent": "center"
	  },
	  "text": {
	    "fontSize": 48
	  }
	}

/***/ }),
/* 3 */
/***/ (function(module, exports) {

	module.exports = function(module, exports, __weex_require__){"use strict";}
	/* generated by weex-loader */


/***/ })
/******/ ]);