// { "framework": "Weex" }
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ (function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(1)
	var __weex_style__ = __webpack_require__(2)
	var __weex_script__ = __webpack_require__(3)

	__weex_define__('@weex-component/381e6901811d5577d5b49d78220b81f0', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})

	__weex_bootstrap__('@weex-component/381e6901811d5577d5b49d78220b81f0',undefined,undefined)

/***/ }),
/* 1 */
/***/ (function(module, exports) {

	module.exports = {
	  "type": "container",
	  "children": [
	    {
	      "type": "text",
	      "id": "top",
	      "attr": {
	        "value": "Top"
	      }
	    },
	    {
	      "type": "container",
	      "style": {
	        "height": 10000,
	        "backgroundColor": "#999999"
	      }
	    },
	    {
	      "type": "text",
	      "events": {
	        "click": "back2Top"
	      },
	      "attr": {
	        "value": "Back to Top"
	      }
	    }
	  ]
	}

/***/ }),
/* 2 */
/***/ (function(module, exports) {

	module.exports = {}

/***/ }),
/* 3 */
/***/ (function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	var dom = __weex_require__('@weex-module/dom');
	module.exports = {
	    data: function () {return {}},
	    methods: {
	        back2Top: function back2Top() {
	            var top = this.$el('top');
	            dom.scrollToElement(top, { offset: 10 });
	        }
	    }
	};}
	/* generated by weex-loader */


/***/ })
/******/ ]);